urls.py
from django.urls import path
from gopesa_app import views
from django.conf.urls import url
#------------------------------------------ END OF IMPORTING LIBRARIES ------------------------------

# APPLICATION NAME

app_name = 'gopesa_app'

# URL PATTERNS FOR APPLICATION "GOPESA_APP"
urlpatterns =[
    path('',views.index,name='index'),
    
    path('properties/',views.properties,name='properties'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('properties/<int:id>/<slug:slug>',views.properties_detail, name="properties_detail")
]
#------------------------------------------ END OF URLS ------------------------------

models.py
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse

# Create your models here.


# MANAGER FOR ACTIVE PROPERTIES
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status="activo")

# TABLE PROPIEDADES

class Propiedades(models.Model):
    objects = models.Manager()      #Our default Manager
    activo = PublishedManager()

    STATUS_CHOICES = (                  # STATUS  CHOICES FOR PROPERTY AVAILABILITY
        ('activo','Activo'),
        ('inactivo','Inactivo'),
    )
    TYPE_CHOICES = (                # TYPE CHOICES FOR PROPERTIES ( EX. IF A HOUSE IS ON SALE, THEN TYPE_CHOICES SHOULD BE SET TO "VENTA")
        ('venta','VENTA'),
        ('renta','RENTA'),

    )

    nombre = models.CharField(max_length=100)   # NAME OF PROPERTY
    slug = models.SlugField(max_length=120)     # SLUG OF PROPERTY ( SLUG  WILL BE USED FOR URL)
    descripcion = models.CharField(max_length=120) # DESCRIPTION
    ubicacion = models.CharField(max_length=100)    # PROPERTY LOCATION
    terreno = models.CharField(max_length=20)       # TOTAL AMOUNT OF M^2
    cuartos = models.CharField(max_length=20)   # ROOMS
    banos = models.CharField(max_length = 20)   # BATHROOMS
    precio = models.CharField(max_length=20)    # PRICE
    tipo = models.CharField(max_length=10, choices=TYPE_CHOICES, default='venta')  # TYPE, USING TYPE_CHOICES FOR DEFINING THE TYPE OF PROPERTY
    status =  models.CharField(max_length=10, choices=STATUS_CHOICES, default='activo') # STATUS OF THE PROPERTY ,SET TO ACTIVE BY DEFAULT, ENABLING A LOGICAL DELETION INSTEAD OF A PHYSICAL ONE.

    class Meta:
        ordering = ['-id']      #PROPERTY_LIST ORDERING, SET TO ID BY DEFAULT


    def __str__(self):
        return self.nombre              # /ADMIN DISPLAY NAME ON DATABASE.

    def get_absolute_url(self):
        return reverse("gopesa_app:properties_detail",args=[self.id,self.slug])   # URL CONSOLIDATION.

#-------------------------- END OF PROPERTY MODEL


# IMAGE MODEL

class Images(models.Model):
    post = models.ForeignKey(Propiedades,on_delete=models.PROTECT)
    image = models.ImageField(upload_to='images/',blank=True,null=True)

    def __str__(self):
        self.post.nombre + "Image"

views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.db.models import Q
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from .models import Propiedades , Images



# Create your views here.

# MANTEINANCE VIEW



# INDEX VIEW ( LANDING PAGE )
def index(request):
    return render(request,"gopesa_app/index.html")
"""
def properties(request):

    return render(request,"principal/properties.html")
"""

#  ABOUT PAGE
def about(request):
    return render(request,"gopesa_app/about.html")

#  CONTACT  PAGE
def contact(request):
    return render(request,"gopesa_app/contact.html")

# def manteinance(request):
#    return render(request,"gopesa_app/manteinance.html")
#  PROPERTIES PAGE ( DISPLAYS LISTS OF PROPERTIES AVAILABLE.)
def properties(request):
    properties_list = Propiedades.activo.all()
    paginator = Paginator(properties_list, 5) # PAGINATION FOR BETTER RESULTS.
    page = request.GET.get('page')
    # VALIDATIONS FOR INCORRECT URLS
    try:
        propiedad = paginator.page(page)
    except PageNotAnInteger:
        propiedad = paginator.page(1)
    except EmptyPage:
        propiedad = paginator.page(paginator.num_pages)

        # INDEX LIMITATION RESULTS
    if page is None:
        start_index = 0
        end_index = 7
    else:
        (start_index, end_index) = proper_pagination(propiedad, index=4)

    page_range = list(paginator.page_range)[start_index:end_index]

    context = {
        'propiedad': propiedad,
        'page_range': page_range,
    }
    return render(request,"gopesa_app/properties.html",context)

# AS THE NAME SAYS, PROPER PAGINATION.
def proper_pagination(propiedad, index):
    start_index = 0
    end_index = 7
    if propiedad.number > index:
        start_index = propiedad.number - index
        end_index = start_index + end_index
    return (start_index, end_index)


# DETAILED VIEW OF AN SPECIFIC PROPERTY, CHARACTERISTICS AND MORE.
def properties_detail(request,id,slug):
    post = get_object_or_404(Propiedades,id=id,slug=slug)
    context={
        'post':post,
    }
    return render(request,'gopesa_app/agents.html',context)


#  -------------------------------- END OF PRINCIPAL:VIEWS ------------------------------

templates/gopesa_app/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!--  UI DESIGN  -->
    <title> GOPESA : ACERCA DE NOSOTROS  </title> <!--  TITULO  -->
    <meta name="description" content="GOPESA Inmobiliaria"><!--  DESCRIPCION  -->
    <meta name="keywords" content=" Inmobiliaria"><!--  PALABRAS CLAVE -->


<!--  CSS  -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
<link rel="stylesheet" href= "{% static 'css/styles-merged.css' %}">
<link rel="stylesheet" href= "{% static 'css/style.min.css' %}">
<link rel="stylesheet" href= "{% static 'css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.min.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>


    <!-- START: header -->

    <div class="probootstrap-loader"></div>

    <header role="banner" class="probootstrap-header">
      <div class="container">
          <a href="{% url 'gopesa_app:index'%}" class="probootstrap-logo"><img src="{%static 'img/logo.png' %}" alt="GOPESA LOGO" style="width:70%;"><span>.</span></a>

          <a href="#" class="probootstrap-burger-menu visible-xs" ><i>Menu</i></a>
          <div class="mobile-menu-overlay"></div>

          <nav role="navigation" class="probootstrap-nav hidden-xs">
            <ul class="probootstrap-main-nav">
              <li ><a href="{% url 'gopesa_app:index'%}">INICIO</a></li>
              <li><a href="{% url 'gopesa_app:properties'%}">Propiedades</a></li>
            <!--  <li><a href="agents.php"></a></li> --> <!--  PROXIMAMENTE -->
              <li class="active"><a href="{% url 'gopesa_app:about'%}">ACERCA DE NOSOTROS</a></li>
              <li><a href="{% url 'gopesa_app:contact'%}">CONTACTO</a></li>
            </ul>
            <div class="extra-text visible-xs">
              <a href="#" class="probootstrap-burger-menu"><i>Menu</i></a>
              <h5>Direccion</h5>
              <p>Prol.Corregidora Norte 913, Local 111, Plaza El Puente. Col. Parques del alam, Queretaro, Qro. CP 76160</p>
              <h5>Redes Sociales </h5>
              <ul class="social-buttons">
                <li><a href="#"><i class="icon-twitter"></i></a></li>
                <li><a href="#"><i class="icon-facebook2"></i></a></li>
                <li><a href="#"><i class="icon-instagram2"></i></a></li>
              </ul>
            </div>
          </nav>
      </div>
    </header>
   <!-- END: header -->


  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="{%url 'gopesa_app:index'%}">INICIO</a><span>ACERCA DE NOSOTROS</span>
              </div>
              <h1>ACERCA DE NOSOTROS</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url({%static 'img/slider_1.jpg'%});"></li>
      <li style="background-image: url({%static 'img/slider_4.jpg'%});"></li>
      <li style="background-image: url({%static 'img/slider_2.jpg'%});"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section">
    <div class="container">
      <div class="row heading">
        <div class="col-md-12"><h2 class="mt0 mb50 text-center">GOPESA Inmobiliaria</h2></div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p><img src="{%static 'img/logo.png'%}" class="img-responsive" alt=""></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <h2>NUESTRA MISION</h2>
          <p>Ofrecemos servicios inmobiliarios integrales en distintos sectores, mediante un servicio de excelencia y profesionalismo</p>
        </div>
        <div class="col-md-6">
          <h2>NUESTRA VISION</h2>
          <p>Ser reconocidos como la compañía inmobiliaria líder en el mercado y preferida por quienes buscan una oportunidad de inversión. </p>
        </div>
      </div>
    </div>
  </section>

  <section class="probootstrap-half">
    <div class="image-wrap">
      <div class="image" style="background-image: url({%static 'img/slider_2.jpg'%});"></div>
    </div>
    <div class="text">
      <p class="mb10 subtitle">Nuestros Valores</p>
      <h3 class="mt0 mb40">Integridad</h3>
      <p>Actuamos con honestidad, congruencia y responsabilidad, fomentando un ambiente de respeto y confianza.</p>
      <p class="mb50"></p>
    <!--  <p><a href="#" class="btn btn-primary mb10">Find out more</a></p> -->
    </div>
  </section>
  <section class="probootstrap-half reverse">
    <div class="image-wrap">
      <div class="image" style="background-image: url({%static 'img/slider_5.jpg'%});"></div>
    </div>
    <div class="text">

      <h3 class="mt0 mb40">Servicio al cliente</h3>
      <p>Brindamos atención de calidad apuntando siempre a la satisfacción total de nuestros clientes.</p>


    </div>
  </section>
   <section class="probootstrap-half">
    <div class="image-wrap">
      <div class="image" style="background-image: url({%static 'img/slider_1.jpg'%});"></div>
    </div>
    <div class="text">
      <p class="mb10 subtitle"></p>
      <h3 class="mt0 mb40">Compromiso</h3>
      <p>Somos conscientes del vínculo que tenemos con nuestros clientes y colaboradores. </p>
      <p class="mb50"></p>

    </div>
  </section>
   <section class="probootstrap-half reverse ">
    <div class="image-wrap">
      <div class="image" style="background-image: url({%static 'img/slider_1.jpg'%});"></div>
    </div>
    <div class="text">
      <p class="mb10 subtitle"></p>
      <h3 class="mt0 mb40">Confidencialidad</h3>
      <p>Garantizamos la protección de la información personal. </p>
      <p class="mb50"></p>

    </div>
  </section>
<!--
  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Miembros del Grupo</h2>
      </div>
      <div class="row">
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{%static 'img/person_1.jpg'%}" class="img-responsive" alt="">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">Alan LLano</h2>
              <p><small>Real Estate Brooker</small></p>

            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{%static 'img/person_2.jpg'%}" class="img-responsive" alt="">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">Arturo Borbolla</h2>
              <p><small>Buying Agent</small></p>

            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{%static 'img/person_2.jpg'%}" class="img-responsive" alt="">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">Arturo Borbolla</h2>
              <p><small>Buying Agent</small></p>

            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{%static 'img/person_2.jpg'%}" class="img-responsive" alt="">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">Arturo Borbolla</h2>
              <p><small>Buying Agent</small></p>

            </div>
          </div>
        </div>

        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{%static 'img/person_2.jpg'%}" class="img-responsive" alt="">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">Arturo Borbolla</h2>
              <p><small>Buying Agent</small></p>

            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{%static 'img/person_2.jpg'%}" class="img-responsive" alt="">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">Arturo Borbolla</h2>
              <p><small>Buying Agent</small></p>

            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{%static 'img/person_2.jpg'%}" class="img-responsive" alt="">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">Arturo Borbolla</h2>
              <p><small>Buying Agent</small></p>

            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{%static 'img/person_2.jpg'%}" class="img-responsive" alt="">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">Arturo Borbolla</h2>
              <p><small>Buying Agent</small></p>

            </div>
          </div>
        </div>


      </div>
    </div>
  </section>

-->



  <footer class="probootstrap-footer probootstrap-bg" style="background-image: url({%static 'img/slider_3.jpg'%})">
    <div class="container">
      <div class="row mb60">
        <div class="col-md-3">
          <div class="probootstrap-footer-widget">
            <h4 class="heading">GOPESA INMOBILIARIA</h4>


          </div>
        </div>


<div class="col-md-3">
          <div class="probootstrap-footer-widget">
            <h4 class="heading">Nuestras Ciudades</h4>
            <ul class="stack-link">
              <li><a href="#">Queretaro <small></small></a></li>
              <li><a href="#">San Miguel de Allende <small></small></a></li>
              <li><a href="#">Tijuana<small></small></a></li>
               </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget probootstrap-link-wrap">


          </div>
        </div>
      </div>
      <div class="row copyright">
        <div class="col-md-6">
          <div class="probootstrap-footer-widget">
            <p>&copy; 2018 <a href="#">GOPESA Inmobiliaria</a></p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="probootstrap-footer-widget right">
            <ul class="probootstrap-footer-social">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>


  <div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-chevron-thin-up"></i></a>
  </div>

  <script src= '{% static "js/scripts.min.js" %}'></script>
  <script src= ' {% static "js/main.min.js" %}'></script>
  <script src= ' {%static "js/custom.js" %}'></script>

  </body>
</html>

templates/gopesa_app/contact.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"> <!--  UI DESIGN  -->
  <title> GOPESA : CONTACTANOS </title> <!--  TITULO  -->
  <meta name="description" content="GOPESA Inmobiliaria"><!--  DESCRIPCION  -->
  <meta name="keywords" content=" Inmobiliaria"><!--  PALABRAS CLAVE -->


<!--  CSS  -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
<link rel="stylesheet" href= "{% static 'css/styles-merged.css' %}">
<link rel="stylesheet" href= "{% static 'css/style.min.css' %}">
<link rel="stylesheet" href= "{% static 'css/custom.css' %}">

  <!--[if lt IE 9]>
    <script src="js/vendor/html5shiv.min.js"></script>
    <script src="js/vendor/respond.min.js"></script>
  <![endif]-->
</head>
  <body>
    <!-- START: header -->

    <div class="probootstrap-loader"></div>

    <header role="banner" class="probootstrap-header">
      <div class="container">
          <a href="{% url 'gopesa_app:index'%}" class="probootstrap-logo"><img src="{%static 'img/logo.png' %}" alt="GOPESA LOGO" style="width:70%;"><span>.</span></a>

          <a href="#" class="probootstrap-burger-menu visible-xs" ><i>Menu</i></a>
          <div class="mobile-menu-overlay"></div>

          <nav role="navigation" class="probootstrap-nav hidden-xs">
            <ul class="probootstrap-main-nav">
              <li ><a href="{% url 'gopesa_app:index'%}">INICIO</a></li>
              <li><a href="{% url 'gopesa_app:properties'%}">Propiedades</a></li>
            <!--  <li><a href="agents.php"></a></li> --> <!--  PROXIMAMENTE -->
              <li><a href="{% url 'gopesa_app:about'%}">ACERCA DE NOSOTROS</a></li>
              <li class="active"><a href="{% url 'gopesa_app:contact'%}">CONTACTO</a></li>
            </ul>
            <div class="extra-text visible-xs">
              <a href="#" class="probootstrap-burger-menu"><i>Menu</i></a>
              <h5>Direccion</h5>
              <p>Prol.Corregidora Norte 913, Local 111, Plaza El Puente. Col. Parques del alam, Queretaro, Qro. CP 76160</p>
              <h5>Redes Sociales</h5>
              <ul class="social-buttons">
                <li><a href="#"><i class="icon-twitter"></i></a></li>
                <li><a href="#"><i class="icon-facebook2"></i></a></li>
                <li><a href="#"><i class="icon-instagram2"></i></a></li>
              </ul>
            </div>
          </nav>
      </div>
    </header>
   <!-- END: header -->


  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="{% url 'gopesa_app:index'%}">Inicio</a><span>Contacto</span>
              </div>
              <h1>CONTACTO</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url({%static 'img/slider_1.jpg' %});"></li>
      <li style="background-image: url( {%static 'img/slider_4.jpg' %});"></li>
      <li style="background-image: url( {%static 'img/slider_2.jpg' %});"></li>
    </ul>
  </section>
  <!-- END: slider  -->
<!--
  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <form action="#" method="post" class="probootstrap-form mb60">
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="fname">Nombre</label>
                  <input type="text" class="form-control" id="fname" name="fname" required >
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="lname">Apellido</label>
                  <input type="text" class="form-control" id="lname" name="lname" required>
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="email">Email</label>
              <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <div class="form-group">
              <label for="message">Mensaje</label>
              <textarea cols="30" rows="10" class="form-control" id="message" name="message" required></textarea>
            </div>
            <div class="form-group">

              <input type="submit" class="btn btn-primary" id="submit" name="submit" value="Send Message">
            </div>
          </form>
	</div> -->
        <div class="col-md-3 col-md-push-1">
          <h4>Informacion de Contacto</h4>
          <ul class="with-icon colored">
            <li><i class="icon-location2"></i> <span>Prol.Corregidora Norte 913, Local 111, Plaza El Puente. Col. Parques del alam, Queretaro, Qro. CP 76160</span></li>
            <li><i class="icon-mail"></i><span>eduardocarrera@ggopesa.com | jlgutierrez@ggopesa.com</span></li>
            <li><i class="icon-phone2"></i><span> 442 476 7167 | 442 138 2668 </span></li>
          </ul>




        </div>
      </div>
    </div>
  </section>
  <div id="map"></div>




  <!--<footer class="probootstrap-footer probootstrap-bg" style="background-image: url(img/slider_3.jpg)">-->
  <footer class="probootstrap-footer probootstrap-bg" style="background-image: url({%static 'img/slider_3.jpg'%})">
    <div class="container">
      <div class="row mb60">
        <div class="col-md-3">
          <div class="probootstrap-footer-widget">
            <h4 class="heading">GOPESA INMOBILIARIA</h4>


          </div>
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget probootstrap-link-wrap">
            <h4 class="heading"></h4>
            <ul class="stack-link">
              <li><a href="#"></a></li>
              <li><a href="#"></a></li>
              <li><a href="#"></a></li>
              <li><a href="#"></a></li>
              <li><a href="#"></a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget">
            <h4 class="heading">Nuestras Ciudades</h4>
            <ul class="stack-link">
              <li><a href="#">Queretaro <small></small></a></li>
              <li><a href="#">San Miguel de Allende <small></small></a></li>
              <li><a href="#">Tijuana<small></small></a></li>
               </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget probootstrap-link-wrap">


          </div>
        </div>
      </div>
      <div class="row copyright">
        <div class="col-md-6">
          <div class="probootstrap-footer-widget">
            <p>&copy; 2018 <a href="#">GOPESA Inmobiliaria</a></p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="probootstrap-footer-widget right">
            <ul class="probootstrap-footer-social">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-chevron-thin-up"></i></a>
  </div>


  <script src= '{% static "js/scripts.min.js" %}'></script>
  <script src= ' {% static "js/main.min.js" %}'></script>
  <script src= ' {%static "js/custom.js" %}'></script>

  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="js/google-map.js"></script>



  </body>
</html>

templates/gopesa_app/properties.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"> <!--  UI DESIGN  -->
  <title> GOPESA : MANTENIMIENTO </title> <!--  TITULO  -->
  <meta name="description" content="GOPESA Inmobiliaria"><!--  DESCRIPCION  -->
  <meta name="keywords" content=" Inmobiliaria"><!--  PALABRAS CLAVE -->


<!--  CSS  -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
<link rel="stylesheet" href= "{% static 'css/styles-merged.css' %}">
<link rel="stylesheet" href= "{% static 'css/style.min.css' %}">
<link rel="stylesheet" href= "{% static 'css/custom.css' %}">

  <!--[if lt IE 9]>
    <script src="js/vendor/html5shiv.min.js"></script>
    <script src="js/vendor/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <img src="{%static 'img/screenshot-4.png'%}" class="img-responsive" alt="Pagina en Mantenimiento">
</body>
</html>